=== alessandrome/RogueRust/src/core/world/map/conf/schema/environments.config.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "name": { "type": "string" },
      "env_type": {
        "type": "string",
        "enum": ["open_world", "dungeon"]
      },
      "attributes": {"type": "object"}
    },
    "required": ["id", "env_type", "attributes"],

    "if": {
      "properties": { "env_type": { "enum": ["open_world"] } }
    },
    "then": {
      "properties": {
        "attributes": {
          "properties": {
            "tiles": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {"type": "string"},
                  "probability": {"type": "integer"}
                },
                "required": ["id", "probability"]
              }
            }
          },
          "required": ["tiles"]
        }
      }
    },
    "else": {
      "if": {
        "properties": { "env_type": { "enum": ["dungeon"] } }
      },
      "then": {
        "properties": {
          "attributes": {
            "properties": {
              "max_rooms": {"type": "integer"},
              "rooms": {
                "type": "array",
                "items": {}
              }
            },
            "required": ["max_rooms", "rooms"]
          }
        }
      }
    }
  }
}

=== alessandrome/RogueRust/src/core/world/map/conf/objs/core/environments.json
[
  {
    "id": "wood",
    "name": "Wood",
    "env_type": "open_world",
    "attributes": {
      "tiles": [
        {"id": "tree", "probability": 90},
        {"id": "grass", "probability": 10}
      ]
    }
  },
  {
    "id": "dungeon",
    "name": "Dungeon",
    "env_type": "dungeon",
    "attributes": {
      "max_rooms": 8,
      "rooms": []
    }
  }
]
